[PARSER]
    Name json
    Format json
    Time_Key timestamp
    Time_Format %Y-%m-%dT%H:%M:%S.%LZ
    Time_Keep On

[PARSER]
    Name docker
    Format json
    Time_Key time
    Time_Format %Y-%m-%dT%H:%M:%S.%L%z

[PARSER]
    Name syslog-rfc3164
    Format regex
    Regex /^(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$/
    Time_Key time
    Time_Format %b %d %H:%M:%S
    Time_Keep On

[PARSER]
    Name syslog-rfc5424
    Format regex
    Regex /^\<(?<pri>[0-9]+)\>(?<version>[0-9]?) (?<time>[^ ]+) (?<host>[^ ]+) (?<ident>[^ ]+) (?<pid>[-0-9#]+) (?<msgid>[^ ]+) (?<extradata>\[-\]|\[.*?\]) (?<message>.*)$/
    Time_Key time
    Time_Format %Y-%m-%dT%H:%M:%S%z
    Time_Keep On

[MULTILINE_PARSER]
    Name java_multiline
    Flush_timeout 1000
    Rule "start_state" "/Exception|Error|SEVERE|FATAL/" "cont"
    Rule "cont" "/^\s+at|^\s+Caused by:|^\s+\.\.\./" "cont"

[MULTILINE_PARSER]
    Name go_multiline
    Flush_timeout 1000
    Rule "start_state" "/panic:|fatal error:/" "cont"
    Rule "cont" "/^\s+.*\.go:/" "cont"
